FROM node:18-alpine AS builder
WORKDIR /app
COPY ui ./ui
WORKDIR /app/ui
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN npm ci && npm run build

FROM nginx:alpine
COPY --from=builder /app/ui/out/ /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK CMD wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
CMD ["nginx", "-g", "daemon off;"]

